config/routes.rb
Depot::Application.routes.draw do

  

  get "store/index"
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end  
  controller :line_items do
    get 'increase_quantity' => :increase_quantity
    get 'decrease_quantity' => :decrease_quantity
  end
  controller :comments do
    post 'show_comments' => :show_comments
    get 'hide_comments' => :hide_comments
    post 'create_for_product_show' => :create_for_product_show
  end
  controller :products do
    get 'change_score' => :change_score
    get 'change_score_for_show' => :change_score_for_show

  end
scope '(:locale)' do
  resources :users
  resources :orders
  resources :line_items
  resources :carts
  resources :comments
  resources :products do
    get :who_bought, :on => :member
  end
  root :to => 'store#index', :as => 'store'
end  
  get 'admin' => 'admin#index'
  
 
  
  
  

  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :product
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :logined
  before_filter :isuer,:only=>[:edit]
  before_filter :authorize,:only => [:destroy]
  # GET /comments
  # GET /comments.xml
  @@per_page = 5
  def index
    @comments = Comment.all
    

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @comments }
    end
  end

  # GET /comments/1
  # GET /comments/1.xml
  def show
    @comment = Comment.find(params[:id])
    

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @comment }
    end
  end

  # GET /comments/new
  # GET /comments/new.xml
  def new
    @comment = Comment.new
    

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @comment }
    end
  end

  # GET /comments/1/edit
  def edit
    @comment = Comment.find(params[:id])
    
  end

  # POST /comments
  # POST /comments.xml
  def create
    @product = Product.find(params[:product_id])
    
    @comment = Comment.new(params[:new_comment])
    @comment.update_attribute('product_id',@product.id)
    
    @comments = Comment.paginate:page=>params[:page],
                                  :order => 'created_at DESC',
                                  :conditions =>["product_id = :pid",{:pid => @product.id}],
                                  :per_page => @@per_page
    @comment_flag = true

    respond_to do |format|
      if @comment.save
        format.html { redirect_to(@comment, :notice => 'Comment was successfully created.') }
        format.js
        format.xml  { render :xml => @comment, :status => :created, :location => @comment }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @comment.errors, :status => :unprocessable_entity }
      end
    end
  end
  def create_for_product_show
    @show_product = Product.find(params[:product_id])
    
    @comment = Comment.new(params[:new_comment])
    @comment.update_attribute('product_id',@show_product.id)
    
    @comments = Comment.paginate:page=>params[:page],
                                  :order => 'created_at DESC',
                                  :conditions =>["product_id = :pid",{:pid => @show_product.id}],
                                  :per_page => @@per_page
    @comment_flag = true

    respond_to do |format|
      if @comment.save
        format.html { redirect_to(@comment, :notice => 'Comment was successfully created.') }
        format.js do
          render :update do |page|
            page.replace_html("product_for_show",render(:partial => "show_product",:object =>@show_product))
          end
        end
        format.xml  { render :xml => @comment, :status => :created, :location => @comment }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @comment.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /comments/1
  # PUT /comments/1.xml
  def update
    @comment = Comment.find(params[:id])
    

    respond_to do |format|
      if @comment.update_attributes(params[:comment])
        format.html { redirect_to(@comment, :notice => 'Comment was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @comment.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.xml
  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    

    respond_to do |format|
      format.html { redirect_to(comments_url) }
      format.xml  { head :ok }
    end
  end
  
  def show_comments
    @product = Product.find(params[:product_id])
#    @comments = Comment.where(:product_id => @product.id)
#    @comments = Comment.find(:all,:conditions =>["product_id = :pid",{:pid => @product.id}])
    @comments = Comment.paginate:page=>params[:page],
                                  :order => 'created_at DESC',
                                  :conditions =>["product_id = :pid",{:pid => @product.id}],
                                  :per_page => @@per_page
    @comment_flag = true
    @new_comment = Comment.new
    
    respond_to do |format|
      format.html {redirect_to(comments_url)}
      format.js   
      format.xml  {head :ok}
    end
  end
  
  def hide_comments
    @comment_flag = false
    @product = Product.find(params[:product_id])
    
    respond_to do |format|
      format.html {redirect_to(comments_url)}
      format.js
      format.xml  {head :ok}
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :product_id %><br />
    <%= f.text_field :product_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/_show_product.html.erb
	<div class="entry">
		<%= image_tag(@show_product.image_url) %>
		<h3><%= @show_product.title %>----------->score:<%= @show_product.score %>----<%= @show_product.score_number %> rated</h3>
		<%=sanitize @show_product.description %>
		
	<div class="shop-rating">
		<ul class="rating-level" id="stars1">
			<li><%= link_to "1",{:controller => "products",:action => "change_score_for_show",:id => @show_product,:score => 1},{:class => "one-star",:remote=>true}%></li>		
			<li><%= link_to "2",{:controller => "products",:action => "change_score_for_show",:id => @show_product,:score => 2},{:class => "two-stars",:remote=>true}%></li>
			<li><%= link_to "3",{:controller => "products",:action => "change_score_for_show",:id => @show_product,:score => 3},{:class => "three-stars",:remote=>true}%></li>
			<li><%= link_to "4",{:controller => "products",:action => "change_score_for_show",:id => @show_product,:score => 4},{:class => "four-stars",:remote=>true}%></li>
			<li><%= link_to "5",{:controller => "products",:action => "change_score_for_show",:id => @show_product,:score => 5},{:class => "five-stars",:remote=>true}%></li>
		</ul>
		<span class="result" id="stars1-tips"></span>
	    <input type="hidden" id="stars1-input" name="b" value="" size="2" />
	</div>
		
		
		
		<div class="price_line">
			<span class="price"><%= number_to_currency(@show_product.price) %></span>
		</div>
	</div>
	
	<div class="comments" id="comments_div">
			<%= form_for :new_comment, :url => {:controller => "comments",
												:action => "create_for_product_show",
												:product_id => @show_product},
												:remote => true do |f|%>
				<div class="field">
				    <%= f.text_area :content, :rows=>3 %>
	  			</div>
	  			<div class="actions">
	    			<%= f.submit %>
				</div>
	  		<% end %>
			<% @comments.each do |comment| %>
				<div class="comments_each">
					<%=sanitize comment.content %>
				</div>
			<% end %>
		<p><%= will_paginate @comments %></p>
	</div>
	
	<%= link_to 'Edit', edit_product_path(@show_product) %> |
	<%= link_to 'Back', products_path %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <tr>
    <th>Product</th>
    <th>User</th>
    <th>Content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @comments.each do |comment| %>
  <tr>
    <td><%= comment.product_id %></td>
    <td><%= comment.user_id %></td>
    <td><%= comment.content %></td>
    <td><%= link_to 'Show', comment %></td>
    <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
    <td><%= link_to 'Destroy', comment, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Product:</b>
  <%= @comment.product_id %>
</p>

<p>
  <b>User:</b>
  <%= @comment.user_id %>
</p>

<p>
  <b>Content:</b>
  <%= @comment.content %>
</p>


<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>