config/routes.rb
Depot::Application.routes.draw do

  

  get "store/index"
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end  
  controller :line_items do
    get 'increase_quantity' => :increase_quantity
    get 'decrease_quantity' => :decrease_quantity
  end
  controller :comments do
    post 'show_comments' => :show_comments
    get 'hide_comments' => :hide_comments
    post 'create_for_product_show' => :create_for_product_show
  end
  controller :products do
    get 'change_score' => :change_score
    get 'change_score_for_show' => :change_score_for_show

  end
scope '(:locale)' do
  resources :users
  resources :orders
  resources :line_items
  resources :carts
  resources :comments
  resources :products do
    get :who_bought, :on => :member
  end
  root :to => 'store#index', :as => 'store'
end  
  get 'admin' => 'admin#index'
  
 
  
  
  

  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title>Pragprog Books Online Store</title>
<%= stylesheet_link_tag "scaffold" %>
<%= stylesheet_link_tag "depot" , :media => "all" %>
<%= stylesheet_link_tag "scores" %>
<%= javascript_include_tag "item_change" %>
<%= javascript_include_tag "mydiv" %>
<%= javascript_include_tag :defaults %>
<%= csrf_meta_tag %>
</head>
<body id="store">
<div id="banner">
<%= image_tag("logo.png" ) %>
<%= @page_title || "Pragmatic Bookshelf" %>
</div>
<div id="columns">
	<div id="side">
		<div id="cart">
			<% if @cart %>
				<%= hidden_div_if(@cart.line_items.empty?,id=>"cart") do %>
				<%= render @cart %>
				<% end %>
			<% end %>
		</div>
	<!--方法二：	<div id="cart"	
			% if @cart.line_items.empty? %>
				style="display:none"
			% end %>
			>
			%= render(:partial => "cart",:object => @cart)%>
	-->
		<a href="./">Home</a><br />
		<a href="http://www..../faq">Questions</a><br />
		<a href="http://www..../news">News</a><br />
		<a href="http://www..../contact">Contact</a><br />
		<% @id = session[:user_id] 
	   @user = User.find(@id) if @id != nil %>
	  
		<% if @user && @user.authority == true%>
			<br />
			<%= link_to 'Orders',orders_path %><br />
			<%= link_to 'Products',products_path %><br />
			<%= link_to 'Users',users_path %><br />
			<br />
			<%= button_to 'Logout',logout_path, :method => :delete %>
		<% elsif @user && @user.authority == false%>
			<br />
			<%= link_to "Hello,#{@user.name}",@user %> <br />
	 		<%= button_to 'Logout', logout_path, :method => :delete %>
	 	<% else%>
	 		<br />
	 		<%= link_to 'Sign In',   login_path     %> <br />
			<%= link_to 'Sign Up', new_user_path %>
		<% end %>
	</div>

	<div id="main">
		<%= yield  %>

	</div>



</div>
</body>
</html>